#!/usr/bin/env python3

"""
git-profile - Setup easily a your profile for git-config
License: BSD 3-Clause
Copyright (c) 2020, Mauro <mauro@sdf.org>
All rights reserved.
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:
1. Redistributions of source code must retain the above copyright
notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright
notice, this list of conditions and the following disclaimer in the
documentation and/or other materials provided with the distribution.
3. Neither the name of the copyright holder nor the names of its
contributors may be used to endorse or promote products derived from
this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""

__author__ = "Mauro L"
__version__ = "0.0.23"
__license__ = "BSD3"

import shlex
import argparse
import subprocess
from pathlib import Path


def git_config(config: str) -> None:
    subprocess.call(shlex.split(f"git config --local {config}"))


def ssh_command(keypath: str) -> str:
    return f"core.sshCommand 'ssh -i {keypath}'"


def user_name(name: str) -> str:
    return f"user.name '{name}'"


def user_email(mail: str) -> str:
    return f"user.email '{mail}'"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Setup easily a profile for git-config"
    )
    parser.add_argument("--ssh", type=str, required=False, help="Use this SSH Key")
    parser.add_argument("--name", type=str, required=False, help="Use this name")
    parser.add_argument("--email", type=str, required=False, help="Use this email")
    args = parser.parse_args()

    if args.ssh and Path(args.ssh).exists():
        git_config(ssh_command(args.ssh))

    if args.name:
        git_config(user_name(args.name))

    if args.email:
        git_config(user_email(args.email))

    if not args.ssh and not args.name and not args.email:
        parser.print_help()
